Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -3,7 +3,7 @@ name: Deploy to Salesforce
 on:
   push:
     branches:
-      - main  # Change to the branch you want to trigger deployment
+      - main
 
 jobs:
   deploy:
@@ -12,16 +12,26 @@ jobs:
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Verify SFDX Project
+        run: |
+          ls -la
+          if [ ! -f "sfdx-project.json" ]; then
+            echo "Error: Not inside an SFDX project!"
+            exit 1
+          fi
 
       - name: Install Salesforce CLI
-        run: |
-          npm install --global sfdx-cli
+        run: npm install --global sfdx-cli
 
-      - name: Authenticate with Salesforce
+      - name: Authenticate with JWT
         run: |
           echo "$SF_SANDBOX_JWT_KEY" > server.key
           sfdx auth jwt grant --client-id "$SF_SANDBOX_CLIENT_ID" --jwt-key-file server.key --username "$SF_SANDBOX_USERNAME" --instance-url "$SF_SANDBOX_URL"
 
-      - name: Deploy Source to Salesforce
+      - name: Deploy to Salesforce
         run: |
+          cd $GITHUB_WORKSPACE
           sfdx force:source:deploy -p force-app -u "$SF_SANDBOX_USERNAME"
